name: cs
on:
  workflow_dispatch:
    inputs:
      arch:
        description: |
          选择 OpenWrt 架构
        required: true
        default: "rockchip-armv8-openwrt"
        type: choice
        options:
          - rockchip-armv8-openwrt
          - x86-64-openwrt
          - armsr-armv8-openwrt
          
      version:
        description: |
          选择 OpenWrt 版本
        required: true
        default: "24.10.1"
        type: choice
        options:
          - 23.05.5
          - 24.10.1
          
      docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
          
      profile:
        description: |
          输入 软路由型号 可选值如下：
        required: true
        default: 'friendlyarm_nanopi-r6s'
        type: choice
        options:
          - friendlyarm_nanopi-r6s
          - xunlong_orangepi-5-plus
          
      rootfs_partsize:
        description: |
          设置软件包大小 单位(MB)
        required: true
        default: '1024'
        type: choice
        options:
          - 512
          - 1024
          - 2048
          - 4096
          
      enable_pppoe:
        description: |
          是否配置PPPoE拨号信息?
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
        
      pppoe_account:
        description: |
          宽带账号 (若启用PPPoE)
        required: false
      pppoe_password:
        description: "宽带密码 (若启用PPPoE)"
        required: false

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}//diy_build/${{ inputs.arch }}/${{ inputs.profile }}/build.sh
           
      - name: Create info
        run: |
          echo "[![Github](https://img.shields.io/badge/Release文件可在国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://ghproxy.net/)" > info.md
          echo "#### 固件地址 \`10.10.10.254\`" >> info.md
          echo "用户名 \`root\` 密码：无" >> info.md
          echo "#### 默认软件包大小 ${{ inputs.rootfs_partsize }}MB" >> info.md
          # [[ "${{ inputs.docker }}" == "yes" ]] && echo "#### 默认带docker" >> info.md
          
      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Actions-Build
          name: ImmortWrt-${{ inputs.arch }}-${{ inputs.version }}
          body_path: info.md
          files: |
            ${{ github.workspace }}/*.img.gz
            ${{ github.workspace }}/*.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}